config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'about' => 'home#about'

  devise_for :users
  resources :users, :controller => "users"

  resources :posts do
    resources :comments
    collection do
      get :mydreams, :userdreams, :dreams_by_tag
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_and_belongs_to_many :tags

  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 50, maximum: 2000 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :update, :edit, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :post_owner_or_admin?, only: [:edit, :update, :destroy]
  before_action :grant_access!, only: [:show]

  def index
    @posts = show_all_dreams(Post.all).order("created_at DESC").page(params[:page]).per(8)
  end

  def mydreams
    @posts = Post.where(user_id: current_user.id).order("created_at DESC").page(params[:page]).per(8)
    render action: 'index'
  end

  def dreams_by_tag
    @tag = Tag.find_by id: params[:tag_id]
    @posts = show_all_dreams(@tag.posts).order("created_at DESC").page(params[:page]).per(8)
    render action: 'index'
  end

  def userdreams
    @posts = show_all_dreams(Post.all).where(user_id: params[:user_id]).order("created_at DESC").page(params[:page]).per(8)
    @user = User.find(params[:user_id]).username
    if user_signed_in? && current_user.username == @user
      redirect_to controller: :posts, action: :mydreams, method: :post
    else
      render action: 'index'
    end
  end

  def new
    @post = Post.new
  end

  def create
    @user = User.find(current_user.id)
    @post = @user.posts.create(post_params)
    if @post.save
      flash[:notice] = "Dream added successfully."
      redirect_to @post
    else
      render 'new'
    end

  end

  def show
    @user_id = @post.user_id
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Dream updated successfully."
      redirect_to @post
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
    @post.destroy
    flash[:notice] = "Dream deleted successfully."
    redirect_to posts_path
  end

  def get_author_by_post_id(post_id)
    User.find(Post.find(post_id).user_id).username
  end
  helper_method :get_author_by_post_id

  private
  def post_params
    params.require(:post).permit(:title, :content, :private, tag_ids:[])
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def show_all_dreams(posts)
    if current_user.try(:admin?)
      posts
    elsif user_signed_in?
      posts.where(user_id: current_user.id).or(posts.where(private: false))
    else
      posts.where(private: false)
    end
  end

  def post_owner_or_admin?
    @user_id = Post.find(params[:id]).user_id
    if (user_signed_in? && current_user.id == @user_id) || current_user.admin?
      return true
    else
      flash[:alert] = "Access denied."
      redirect_to root_path
    end
  end

  def post_private?
    Post.find(params[:id]).private
  end

  def grant_access!
    if post_private? && post_owner_or_admin?
      return true
    elsif !post_private?
      return true
    else
      return false
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
<%= f.input :title, label: false, placeholder: "Dream name" %>
<%= f.input :content, label: false, placeholder: "Describe your dream here.", input_html: { class: "mt-4 h-64" } %>

<div class="flex flex-wrap mt-2 mb-6">
  <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |t| %>
  <label class="flex justify-start items-start mt-2 inline-block w-40 text-sm">
    <div class="inline-block bg-white border rounded border-gray-600 w-6 h-6 flex flex-shrink-0 justify-center items-center mr-2 focus-within:border-blue-500">
      <%= t.check_box class: "hidden" %>
      <svg class="fill-current hidden w-4 h-4 text-teal-600 pointer-events-none" viewBox="0 0 20 20"><path d="M0 11l2-2 5 5L18 3l2 2L7 18z"/></svg>
    </div>
    <div class="select-none"><%= t.label %></div>
    </label>
  <% end %>
</div>


<label class="flex justify-start items-start mt-4">
  <div class="bg-white border rounded border-gray-600 w-6 h-6 flex flex-shrink-0 justify-center items-center mr-2 focus-within:border-blue-500">
    <%= f.check_box :private, as: :boolean, label: false, wrapper: false, class: "hidden" %>
    <svg class="fill-current hidden w-4 h-4 text-teal-600 pointer-events-none" viewBox="0 0 20 20"><path d="M0 11l2-2 5 5L18 3l2 2L7 18z"/></svg>
  </div>
  <div class="select-none">Private Dream</div>
</label>
<%= f.button :submit, button_name, class: "mt-4" %>
<% end %>

app/views/posts/edit.html.erb
<% content_for :title, "Edit Dream - DreamDiary.online" %>
<div class="justify-center w-full">
  <div>
    <h2 class="mb-4">Edit Dream</h2>
    <%= render partial: 'form', locals: { button_name: "Edit Dream" } %>
  </div>
</div>

app/views/posts/index.html.erb
<% content_for :title, "DreamDiary.online" %>
<%= @dupa %>
<div class="w-full">
  <% if !user_signed_in? %>
    <section class="text-gray-600 mb-4"><%= get_welcome_text %></section>
  <% end %>
  <% if !flash.empty? %>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key} w-auto inline-block" %>
    <% end %>
  <% end %>
  <%= get_header_info(@user) %>
  <% if @posts.count == 0 %>
    <%= "Nothing here yet." %>
  <% end %>
  <% @posts.each do |post| %>
    <section class="pb-4">
      <div class="border-b border-gray-300 pb-2 md:pb-6">
        <article>
          <h3 class="mb-2"><%= link_to post.title, post %></h3>
          <%= simple_format truncate(post.content, length: 250) { link_to " read more", post } %>
          <div class="tags mt-2">
            <% post.tags.each do |t| %>
              <%= active_link_to t.name, dreams_by_tag_posts_path(:tag_id => t.id), active: :exact %>
            <% end %>
          </div>
          <p class="mt-2"><%= get_author_and_time(post) %></p>
          <p><%= link_to get_comments_count(post), post_path(post, anchor: 'comments') %></p>
        </article>
        <div class="relative">
          <% if (user_signed_in? && current_user.id == post.user_id) || current_user.try(:admin?) %>
            <div class="md:absolute flex justify-end mt-2 md:-mt-4 right-0 top-0 flex">
              <% if post.private %><span class="private text-xs mr-2 md:mr-0">Private</span><% end %>
              <%= link_to "Edit", edit_post_path(post), method: :get, :class => "btn md:ml-2 mr-2 inline-block" %>
              <%= link_to "Delete", post_path(post), method: :delete, data: { confirm: "Are you sure?" }, :class => "btn del inline-block" %>
            </div>
          <% end %>
        </div>
      </div>
    </section>
  <% end %>
  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<% content_for :title, "New Dream - DreamDiary.online" %>
<div class="justify-center w-full">
  <div>
    <h2 class="mb-4">New Dream</h2>
    <%= render partial: 'form', locals: { button_name: "Add Dream" } %>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for :title, @post.title + " - DreamDiary.online" %>
<div class="w-full">
  <% if !flash.empty? %>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key} mb-4 w-auto inline-block" %>
    <% end %>
  <% end %>
  <section>
    <article>
      <h3 class="mb-2"><%= @post.title %></h3>
      <%= simple_format @post.content %>
      <div class="tags mt-2">
        <% @post.tags.each do |t| %>
          <%= active_link_to t.name, dreams_by_tag_posts_path(:tag_id => t.id), active: :exact %>
        <% end %>
      </div>
      <div class="flex flex-wrap">
        <div class="mt-2"><%= get_author_and_time(@post) %></div>
        <% if (user_signed_in? && current_user.id == @post.user_id) || current_user.try(:admin?)%>
          <div class="pt-4 flex-auto text-right">
            <% if @post.private %><span class="private mr-1">Private</span><% end %>
            <%= link_to "Edit", edit_post_path(@post), method: :get, :class => "btn mr-1" %>
            <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, :class => "btn del" %>
          </div>
        </div>
      <% end %>
    </article>
  </section>
  <section class="mt-8" id="comments">
    <p class="border border-t-1 border-b-0 border-l-0 border-r-0 pt-2"><%= get_comments_count(@post) %></p>
    <%= render @post.comments %>
    <% if user_signed_in? %>
      <h4 class="text-xl mb-2">Leave a comment</h4>
      <%= render 'comments/form' %>
    <% else %>
      <p class="mt-2">You must <%= active_link_to 'Log in', new_user_session_path %> to add a comment. </p>
    <% end %>
  </section>
</div>