config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'about' => 'home#about'

  devise_for :users
  resources :users, :controller => "users"

  resources :posts do
    resources :comments
    collection do
      get :mydreams, :userdreams, :dreams_by_tag
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="You dream about 100 minutes every night, but forget 95% of your dreams. Log them with DreamDiary.online instead.">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-159138064-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-159138064-1');
    </script>
  </head>
  <body class="bg-gray-200 text-gray-800 pb-4 bg-right-bottom bg-no-repeat bg-contain bg-local md:bg-fixed" style="background-image: url('/assets/bg.png');">
    <div class="container mx-auto px-4 md:pl-40 bg-no-repeat bg-right-top md:bg-left-top">
      <header class="relative">
        <div class="h-16 md:h-20 max-w-xs md:max-w-md pt-4 mb-4">
          <h1 class="text-3xl md:text-5xl tracking-wider p-0 leading-none" style="font-family: 'Unna-Bold'">
            <%= link_to get_logo, root_path, class: "text-gray-800" %>
          </h1>
          <span class="text-gray-700 italic text-sm md:text-base absolute -mt-1 md:-mt-2 tracking-wide" style="font-family: 'Unna-Italic'">all your dreams in one place</span>
        </div>
        <div class="md:absolute md:top-0 md:right-0 mt-4 mb-4 md:mb-0">
          <% if user_signed_in? %>
            <%= current_user.username %>
            <%= active_link_to 'Sign out', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= active_link_to 'Log in', new_user_session_path %>
            <%= active_link_to "Sign up", new_user_registration_path %>
          <% end %>
        </div>
        <% if user_signed_in? %>
          <nav class="flex justify-center md:justify-start my-4">
            <ul class="flex flex-col lg:flex-row flex-grow text-center lg:text-left">
                <li class="md:mr-2 mb-2 lg:mb-0 max-w-xs"><%= active_link_to 'Add a new dream', new_post_path,  :class => "btn min-w-full" %>
                <li class="md:mr-2 mb-2 lg:mb-0 max-w-xs"><%= active_link_to 'Show all dreams', root_path, active: :exact, :class => "btn min-w-full" %>
                <li class="md:mr-2 mb-2 lg:mb-0 max-w-xs"><%= active_link_to 'Show my dreams only', mydreams_posts_path, :class => "btn min-w-full" %>
                <% if current_user.try(:admin?) %>
                  <li class="md:mr-3 max-w-xs"><%= active_link_to 'Show users', users_path, :class => "btn min-w-full" %>
                <% end %>
            </ul>
          </nav>
        <% end %>
      </header>
      <div class="md:flex">
        <main class="w-full md:w-3/4">
          <%= yield %>
        </main>
        <aside class="md:w-1/4 md:pl-8 mt-4 md:mt-0 text-center">
          <h4 class="text-xl font-bold mb-2">Tags</h4>
          <ul class="tags border-b border-gray-300 pb-3 mb-4 flex flex-wrap justify-center">
            <% Tag.all.each do |t| %>
              <li class="mb-1 mr-4"><%= active_link_to t.name, dreams_by_tag_posts_path(:tag_id => t.id), active: :exact %></li>
            <% end %>
          </ul>
          <ul class="border-b border-gray-300 pb-3 mb-4">
            <h4 class="text-xl font-bold mb-2">Stats</h4>
            <li class="mb-1">Total Dreams: <%= get_number_of_dreams %></li>
            <li class="mb-1">Total Dreamers: <%= get_number_of_dreamers %></li>
            <li>Private Dreams: <%= get_number_of_private_dreams %></li>
          </ul>
          <%= active_link_to 'About', about_path %>
        </aside>
      </div>
      <footer class="text-center my-8">
        <%= get_footer %>
      </footer>
    </div>
    <script>
      function validate() {
        let inputError = document.getElementById('inputError');
        let new_comment = document.getElementById('new_comment');
        let input = document.forms["new_comment"]["comment_comment"].value;
          if (input.length > 0) {
            inputError.innerText = "";
            return true;
          }
          else {
            inputError.innerText = "comment can't be blank";
            inputError.classList.add("mt-2");
            return false;
          }
        }
    </script>
  </body>
</html>